### ISSUE TITLE
Experiment Result

### ISSUE THREAD

**Issue by 854811200** [DAA233/generative-inpainting-pytorch#1]
Can you post some result image in the README file, thanks.

**Comment by DAA233** [comment]
@854811200 Yes, I can post some image results in the README next week. I have trained the model on ImageNet and Places2 dataset. However, maybe caused by bugs in the code, the results look poor compared with the original implementation.  Some results on ImageNet have been posted in this [issue](https://github.com/JiahuiYu/generative_inpainting/issues/202).

**Comment by DAA233** [comment]
I am sorry that it has been a long time since I said to update the results. Now I have fixed some bugs in the contextual attention module and retrained the model. Some test results have been put in the README.
