### ISSUE TITLE
Same model, different result?

### ISSUE THREAD

**Issue by canopyPanda** [DAA233/generative-inpainting-pytorch#6]
Hi，I use the pre-trained model offered by you,  and I change the "network.py" file to test the "test_single.py", why I get different results with yours?
    
![output](https://user-images.githubusercontent.com/18417400/60398437-99d25000-9b8a-11e9-9dc0-4bbfb726c0af.png)
![output_1](https://user-images.githubusercontent.com/18417400/60398438-9a6ae680-9b8a-11e9-9053-fc6810a3a320.png)
![output_2](https://user-images.githubusercontent.com/18417400/60398439-9a6ae680-9b8a-11e9-8a7b-d21a39f1a5eb.png)
![output_3](https://user-images.githubusercontent.com/18417400/60398440-9b037d00-9b8a-11e9-952e-abc093887ae5.png)
![output_4](https://user-images.githubusercontent.com/18417400/60398441-9b037d00-9b8a-11e9-9bb3-0734e450e1d9.png)

**Comment by DAA233** [comment]
Sorry about the confusion. The model was trained based on [this version](https://github.com/DAA233/generative-inpainting-pytorch/tree/aff88a1729365c1bc0bce3e975745ec1846968ca). There are several commits after then and some layers' channel numbers and the contextual attention module has been modified. Although you have modified the networks to load the pre-trained model, there are still some different operations in other parts, such as the contextual attention module. I think that's why you get different results. 

I am training a model from scratch based on the latest version. Once it is done, I will update the model links and the test results.
